export interface CurriculumEntry {
  surahNumber: number
  name: string
  englishName: string
  ayahCount: number
  phase: 1 | 2 | 3 | 4
}

export const CURRICULUM: CurriculumEntry[] = [
  // Phase 1: Juz 30 — Foundation (shortest → longest)
  { surahNumber: 110, name: 'An-Nasr', englishName: 'The Help', ayahCount: 3, phase: 1 },
  { surahNumber: 108, name: 'Al-Kawthar', englishName: 'The Abundance', ayahCount: 3, phase: 1 },
  { surahNumber: 103, name: 'Al-Asr', englishName: 'The Declining Day', ayahCount: 3, phase: 1 },
  { surahNumber: 112, name: 'Al-Ikhlas', englishName: 'Sincerity', ayahCount: 4, phase: 1 },
  { surahNumber: 106, name: 'Quraysh', englishName: 'Quraysh', ayahCount: 4, phase: 1 },
  { surahNumber: 113, name: 'Al-Falaq', englishName: 'The Daybreak', ayahCount: 5, phase: 1 },
  { surahNumber: 111, name: 'Al-Masad', englishName: 'The Palm Fiber', ayahCount: 5, phase: 1 },
  { surahNumber: 105, name: 'Al-Fil', englishName: 'The Elephant', ayahCount: 5, phase: 1 },
  { surahNumber: 97, name: 'Al-Qadr', englishName: 'The Night of Power', ayahCount: 5, phase: 1 },
  { surahNumber: 114, name: 'An-Nas', englishName: 'The Mankind', ayahCount: 6, phase: 1 },
  { surahNumber: 109, name: 'Al-Kafirun', englishName: 'The Disbelievers', ayahCount: 6, phase: 1 },
  { surahNumber: 107, name: "Al-Ma'un", englishName: 'The Small Kindnesses', ayahCount: 7, phase: 1 },
  { surahNumber: 102, name: 'At-Takathur', englishName: 'The Rivalry in World Increase', ayahCount: 8, phase: 1 },
  { surahNumber: 99, name: 'Az-Zalzalah', englishName: 'The Earthquake', ayahCount: 8, phase: 1 },
  { surahNumber: 98, name: 'Al-Bayyinah', englishName: 'The Clear Proof', ayahCount: 8, phase: 1 },
  { surahNumber: 95, name: 'At-Tin', englishName: 'The Fig', ayahCount: 8, phase: 1 },
  { surahNumber: 94, name: 'Ash-Sharh', englishName: 'The Relief', ayahCount: 8, phase: 1 },
  { surahNumber: 104, name: 'Al-Humazah', englishName: 'The Slanderer', ayahCount: 9, phase: 1 },
  { surahNumber: 101, name: "Al-Qari'ah", englishName: 'The Calamity', ayahCount: 11, phase: 1 },
  { surahNumber: 100, name: 'Al-Adiyat', englishName: 'The Courser', ayahCount: 11, phase: 1 },
  { surahNumber: 93, name: 'Ad-Duha', englishName: 'The Morning Hours', ayahCount: 11, phase: 1 },
  { surahNumber: 91, name: 'Ash-Shams', englishName: 'The Sun', ayahCount: 15, phase: 1 },
  { surahNumber: 86, name: 'At-Tariq', englishName: 'The Morning Star', ayahCount: 17, phase: 1 },
  { surahNumber: 96, name: 'Al-Alaq', englishName: 'The Clot', ayahCount: 19, phase: 1 },
  { surahNumber: 87, name: "Al-A'la", englishName: 'The Most High', ayahCount: 19, phase: 1 },
  { surahNumber: 82, name: 'Al-Infitar', englishName: 'The Cleaving', ayahCount: 19, phase: 1 },
  { surahNumber: 90, name: 'Al-Balad', englishName: 'The City', ayahCount: 20, phase: 1 },
  { surahNumber: 92, name: 'Al-Layl', englishName: 'The Night', ayahCount: 21, phase: 1 },
  { surahNumber: 85, name: 'Al-Buruj', englishName: 'The Constellations', ayahCount: 22, phase: 1 },
  { surahNumber: 84, name: 'Al-Inshiqaq', englishName: 'The Sundering', ayahCount: 25, phase: 1 },
  { surahNumber: 88, name: 'Al-Ghashiyah', englishName: 'The Overwhelming', ayahCount: 26, phase: 1 },
  { surahNumber: 81, name: 'At-Takwir', englishName: 'The Overthrowing', ayahCount: 29, phase: 1 },
  { surahNumber: 89, name: 'Al-Fajr', englishName: 'The Dawn', ayahCount: 30, phase: 1 },
  { surahNumber: 83, name: 'Al-Mutaffifin', englishName: 'The Defrauding', ayahCount: 36, phase: 1 },
  { surahNumber: 78, name: "An-Naba'", englishName: 'The Announcement', ayahCount: 40, phase: 1 },
  { surahNumber: 80, name: 'Abasa', englishName: 'He Frowned', ayahCount: 42, phase: 1 },
  { surahNumber: 79, name: "An-Nazi'at", englishName: 'Those Who Drag Forth', ayahCount: 46, phase: 1 },

  // Phase 2: Juz 29 — Building Stamina (shortest → longest)
  { surahNumber: 73, name: 'Al-Muzzammil', englishName: 'The Enshrouded One', ayahCount: 20, phase: 2 },
  { surahNumber: 72, name: 'Al-Jinn', englishName: 'The Jinn', ayahCount: 28, phase: 2 },
  { surahNumber: 71, name: 'Nuh', englishName: 'Noah', ayahCount: 28, phase: 2 },
  { surahNumber: 67, name: 'Al-Mulk', englishName: 'The Sovereignty', ayahCount: 30, phase: 2 },
  { surahNumber: 76, name: 'Al-Insan', englishName: 'The Human', ayahCount: 31, phase: 2 },
  { surahNumber: 75, name: 'Al-Qiyamah', englishName: 'The Resurrection', ayahCount: 40, phase: 2 },
  { surahNumber: 70, name: "Al-Ma'arij", englishName: 'The Ascending Stairways', ayahCount: 44, phase: 2 },
  { surahNumber: 77, name: 'Al-Mursalat', englishName: 'The Emissaries', ayahCount: 50, phase: 2 },
  { surahNumber: 69, name: 'Al-Haqqah', englishName: 'The Reality', ayahCount: 52, phase: 2 },
  { surahNumber: 68, name: 'Al-Qalam', englishName: 'The Pen', ayahCount: 52, phase: 2 },
  { surahNumber: 74, name: 'Al-Muddathir', englishName: 'The Cloaked One', ayahCount: 56, phase: 2 },

  // Phase 3: Key Surahs — High Motivation
  { surahNumber: 1, name: 'Al-Fatihah', englishName: 'The Opening', ayahCount: 7, phase: 3 },
  { surahNumber: 36, name: 'Ya-Sin', englishName: 'Ya-Sin', ayahCount: 83, phase: 3 },
  { surahNumber: 55, name: 'Ar-Rahman', englishName: 'The Most Gracious', ayahCount: 78, phase: 3 },
  { surahNumber: 56, name: "Al-Waqi'ah", englishName: 'The Inevitable', ayahCount: 96, phase: 3 },
  { surahNumber: 18, name: 'Al-Kahf', englishName: 'The Cave', ayahCount: 110, phase: 3 },
  { surahNumber: 32, name: 'As-Sajdah', englishName: 'The Prostration', ayahCount: 30, phase: 3 },
  { surahNumber: 44, name: 'Ad-Dukhan', englishName: 'The Smoke', ayahCount: 59, phase: 3 },
  { surahNumber: 48, name: 'Al-Fath', englishName: 'The Victory', ayahCount: 29, phase: 3 },
  { surahNumber: 49, name: 'Al-Hujurat', englishName: 'The Rooms', ayahCount: 18, phase: 3 },
  { surahNumber: 57, name: 'Al-Hadid', englishName: 'The Iron', ayahCount: 29, phase: 3 },

  // Phase 4: Remaining Surahs — Full Hifz (Mushaf order)
  { surahNumber: 2, name: 'Al-Baqarah', englishName: 'The Cow', ayahCount: 286, phase: 4 },
  { surahNumber: 3, name: 'Aal-E-Imran', englishName: 'The Family of Imran', ayahCount: 200, phase: 4 },
  { surahNumber: 4, name: "An-Nisa'", englishName: 'The Women', ayahCount: 176, phase: 4 },
  { surahNumber: 5, name: "Al-Ma'idah", englishName: 'The Table Spread', ayahCount: 120, phase: 4 },
  { surahNumber: 6, name: "Al-An'am", englishName: 'The Cattle', ayahCount: 165, phase: 4 },
  { surahNumber: 7, name: "Al-A'raf", englishName: 'The Heights', ayahCount: 206, phase: 4 },
  { surahNumber: 8, name: 'Al-Anfal', englishName: 'The Spoils of War', ayahCount: 75, phase: 4 },
  { surahNumber: 9, name: 'At-Tawbah', englishName: 'The Repentance', ayahCount: 129, phase: 4 },
  { surahNumber: 10, name: 'Yunus', englishName: 'Jonah', ayahCount: 109, phase: 4 },
  { surahNumber: 11, name: 'Hud', englishName: 'Hud', ayahCount: 123, phase: 4 },
  { surahNumber: 12, name: 'Yusuf', englishName: 'Joseph', ayahCount: 111, phase: 4 },
  { surahNumber: 13, name: "Ar-Ra'd", englishName: 'The Thunder', ayahCount: 43, phase: 4 },
  { surahNumber: 14, name: 'Ibrahim', englishName: 'Abraham', ayahCount: 52, phase: 4 },
  { surahNumber: 15, name: 'Al-Hijr', englishName: 'The Rocky Tract', ayahCount: 99, phase: 4 },
  { surahNumber: 16, name: 'An-Nahl', englishName: 'The Bee', ayahCount: 128, phase: 4 },
  { surahNumber: 17, name: "Al-Isra'", englishName: 'The Night Journey', ayahCount: 111, phase: 4 },
  { surahNumber: 19, name: 'Maryam', englishName: 'Mary', ayahCount: 98, phase: 4 },
  { surahNumber: 20, name: 'Ta-Ha', englishName: 'Ta-Ha', ayahCount: 135, phase: 4 },
  { surahNumber: 21, name: "Al-Anbiya'", englishName: 'The Prophets', ayahCount: 112, phase: 4 },
  { surahNumber: 22, name: 'Al-Hajj', englishName: 'The Pilgrimage', ayahCount: 78, phase: 4 },
  { surahNumber: 23, name: "Al-Mu'minun", englishName: 'The Believers', ayahCount: 118, phase: 4 },
  { surahNumber: 24, name: 'An-Nur', englishName: 'The Light', ayahCount: 64, phase: 4 },
  { surahNumber: 25, name: 'Al-Furqan', englishName: 'The Criterion', ayahCount: 77, phase: 4 },
  { surahNumber: 26, name: "Ash-Shu'ara'", englishName: 'The Poets', ayahCount: 227, phase: 4 },
  { surahNumber: 27, name: 'An-Naml', englishName: 'The Ant', ayahCount: 93, phase: 4 },
  { surahNumber: 28, name: 'Al-Qasas', englishName: 'The Stories', ayahCount: 88, phase: 4 },
  { surahNumber: 29, name: 'Al-Ankabut', englishName: 'The Spider', ayahCount: 69, phase: 4 },
  { surahNumber: 30, name: 'Ar-Rum', englishName: 'The Romans', ayahCount: 60, phase: 4 },
  { surahNumber: 31, name: 'Luqman', englishName: 'Luqman', ayahCount: 34, phase: 4 },
  { surahNumber: 33, name: 'Al-Ahzab', englishName: 'The Combined Forces', ayahCount: 73, phase: 4 },
  { surahNumber: 34, name: "Saba'", englishName: 'Sheba', ayahCount: 54, phase: 4 },
  { surahNumber: 35, name: 'Fatir', englishName: 'The Originator', ayahCount: 45, phase: 4 },
  { surahNumber: 37, name: 'As-Saffat', englishName: 'Those Who Set the Ranks', ayahCount: 182, phase: 4 },
  { surahNumber: 38, name: 'Sad', englishName: 'Sad', ayahCount: 88, phase: 4 },
  { surahNumber: 39, name: 'Az-Zumar', englishName: 'The Troops', ayahCount: 75, phase: 4 },
  { surahNumber: 40, name: 'Ghafir', englishName: 'The Forgiver', ayahCount: 85, phase: 4 },
  { surahNumber: 41, name: 'Fussilat', englishName: 'Explained in Detail', ayahCount: 54, phase: 4 },
  { surahNumber: 42, name: 'Ash-Shura', englishName: 'The Consultation', ayahCount: 53, phase: 4 },
  { surahNumber: 43, name: 'Az-Zukhruf', englishName: 'The Ornaments of Gold', ayahCount: 89, phase: 4 },
  { surahNumber: 45, name: 'Al-Jathiyah', englishName: 'The Crouching', ayahCount: 37, phase: 4 },
  { surahNumber: 46, name: 'Al-Ahqaf', englishName: 'The Wind-Curved Sandhills', ayahCount: 35, phase: 4 },
  { surahNumber: 47, name: 'Muhammad', englishName: 'Muhammad', ayahCount: 38, phase: 4 },
  { surahNumber: 50, name: 'Qaf', englishName: 'Qaf', ayahCount: 45, phase: 4 },
  { surahNumber: 51, name: 'Adh-Dhariyat', englishName: 'The Winnowing Winds', ayahCount: 60, phase: 4 },
  { surahNumber: 52, name: 'At-Tur', englishName: 'The Mount', ayahCount: 49, phase: 4 },
  { surahNumber: 53, name: 'An-Najm', englishName: 'The Star', ayahCount: 62, phase: 4 },
  { surahNumber: 54, name: 'Al-Qamar', englishName: 'The Moon', ayahCount: 55, phase: 4 },
  { surahNumber: 58, name: 'Al-Mujadila', englishName: 'The Pleading Woman', ayahCount: 22, phase: 4 },
  { surahNumber: 59, name: 'Al-Hashr', englishName: 'The Exile', ayahCount: 24, phase: 4 },
  { surahNumber: 60, name: 'Al-Mumtahanah', englishName: 'She That Is to Be Examined', ayahCount: 13, phase: 4 },
  { surahNumber: 61, name: 'As-Saff', englishName: 'The Ranks', ayahCount: 14, phase: 4 },
  { surahNumber: 62, name: "Al-Jumu'ah", englishName: 'The Congregation', ayahCount: 11, phase: 4 },
  { surahNumber: 63, name: 'Al-Munafiqun', englishName: 'The Hypocrites', ayahCount: 11, phase: 4 },
  { surahNumber: 64, name: 'At-Taghabun', englishName: 'The Mutual Disillusion', ayahCount: 18, phase: 4 },
  { surahNumber: 65, name: 'At-Talaq', englishName: 'The Divorce', ayahCount: 12, phase: 4 },
  { surahNumber: 66, name: 'At-Tahrim', englishName: 'The Prohibition', ayahCount: 12, phase: 4 },
]

/** Conservative average — used for user-facing estimates on dashboard */
export const AVG_WORDS_PER_AYAH = 10

/** Approximate number of unique (distinct) words in the Quran */
export const TOTAL_UNIQUE_WORDS = 14870

export function getPhaseLabel(phase: 1 | 2 | 3 | 4): string {
  const labels: Record<number, string> = {
    1: 'Juz 30 — Foundation',
    2: 'Juz 29 — Building Stamina',
    3: 'Key Surahs',
    4: 'Full Hifz',
  }
  return labels[phase]
}

// All 114 surahs in Mushaf order for the onboarding checklist
export const ALL_SURAHS: { surahNumber: number; name: string; ayahCount: number }[] = [
  { surahNumber: 1, name: 'Al-Fatihah', ayahCount: 7 },
  { surahNumber: 2, name: 'Al-Baqarah', ayahCount: 286 },
  { surahNumber: 3, name: 'Aal-E-Imran', ayahCount: 200 },
  { surahNumber: 4, name: "An-Nisa'", ayahCount: 176 },
  { surahNumber: 5, name: "Al-Ma'idah", ayahCount: 120 },
  { surahNumber: 6, name: "Al-An'am", ayahCount: 165 },
  { surahNumber: 7, name: "Al-A'raf", ayahCount: 206 },
  { surahNumber: 8, name: 'Al-Anfal', ayahCount: 75 },
  { surahNumber: 9, name: 'At-Tawbah', ayahCount: 129 },
  { surahNumber: 10, name: 'Yunus', ayahCount: 109 },
  { surahNumber: 11, name: 'Hud', ayahCount: 123 },
  { surahNumber: 12, name: 'Yusuf', ayahCount: 111 },
  { surahNumber: 13, name: "Ar-Ra'd", ayahCount: 43 },
  { surahNumber: 14, name: 'Ibrahim', ayahCount: 52 },
  { surahNumber: 15, name: 'Al-Hijr', ayahCount: 99 },
  { surahNumber: 16, name: 'An-Nahl', ayahCount: 128 },
  { surahNumber: 17, name: "Al-Isra'", ayahCount: 111 },
  { surahNumber: 18, name: 'Al-Kahf', ayahCount: 110 },
  { surahNumber: 19, name: 'Maryam', ayahCount: 98 },
  { surahNumber: 20, name: 'Ta-Ha', ayahCount: 135 },
  { surahNumber: 21, name: "Al-Anbiya'", ayahCount: 112 },
  { surahNumber: 22, name: 'Al-Hajj', ayahCount: 78 },
  { surahNumber: 23, name: "Al-Mu'minun", ayahCount: 118 },
  { surahNumber: 24, name: 'An-Nur', ayahCount: 64 },
  { surahNumber: 25, name: 'Al-Furqan', ayahCount: 77 },
  { surahNumber: 26, name: "Ash-Shu'ara'", ayahCount: 227 },
  { surahNumber: 27, name: 'An-Naml', ayahCount: 93 },
  { surahNumber: 28, name: 'Al-Qasas', ayahCount: 88 },
  { surahNumber: 29, name: 'Al-Ankabut', ayahCount: 69 },
  { surahNumber: 30, name: 'Ar-Rum', ayahCount: 60 },
  { surahNumber: 31, name: 'Luqman', ayahCount: 34 },
  { surahNumber: 32, name: 'As-Sajdah', ayahCount: 30 },
  { surahNumber: 33, name: 'Al-Ahzab', ayahCount: 73 },
  { surahNumber: 34, name: "Saba'", ayahCount: 54 },
  { surahNumber: 35, name: 'Fatir', ayahCount: 45 },
  { surahNumber: 36, name: 'Ya-Sin', ayahCount: 83 },
  { surahNumber: 37, name: 'As-Saffat', ayahCount: 182 },
  { surahNumber: 38, name: 'Sad', ayahCount: 88 },
  { surahNumber: 39, name: 'Az-Zumar', ayahCount: 75 },
  { surahNumber: 40, name: 'Ghafir', ayahCount: 85 },
  { surahNumber: 41, name: 'Fussilat', ayahCount: 54 },
  { surahNumber: 42, name: 'Ash-Shura', ayahCount: 53 },
  { surahNumber: 43, name: 'Az-Zukhruf', ayahCount: 89 },
  { surahNumber: 44, name: 'Ad-Dukhan', ayahCount: 59 },
  { surahNumber: 45, name: 'Al-Jathiyah', ayahCount: 37 },
  { surahNumber: 46, name: 'Al-Ahqaf', ayahCount: 35 },
  { surahNumber: 47, name: 'Muhammad', ayahCount: 38 },
  { surahNumber: 48, name: 'Al-Fath', ayahCount: 29 },
  { surahNumber: 49, name: 'Al-Hujurat', ayahCount: 18 },
  { surahNumber: 50, name: 'Qaf', ayahCount: 45 },
  { surahNumber: 51, name: 'Adh-Dhariyat', ayahCount: 60 },
  { surahNumber: 52, name: 'At-Tur', ayahCount: 49 },
  { surahNumber: 53, name: 'An-Najm', ayahCount: 62 },
  { surahNumber: 54, name: 'Al-Qamar', ayahCount: 55 },
  { surahNumber: 55, name: 'Ar-Rahman', ayahCount: 78 },
  { surahNumber: 56, name: "Al-Waqi'ah", ayahCount: 96 },
  { surahNumber: 57, name: 'Al-Hadid', ayahCount: 29 },
  { surahNumber: 58, name: 'Al-Mujadila', ayahCount: 22 },
  { surahNumber: 59, name: 'Al-Hashr', ayahCount: 24 },
  { surahNumber: 60, name: 'Al-Mumtahanah', ayahCount: 13 },
  { surahNumber: 61, name: 'As-Saff', ayahCount: 14 },
  { surahNumber: 62, name: "Al-Jumu'ah", ayahCount: 11 },
  { surahNumber: 63, name: 'Al-Munafiqun', ayahCount: 11 },
  { surahNumber: 64, name: 'At-Taghabun', ayahCount: 18 },
  { surahNumber: 65, name: 'At-Talaq', ayahCount: 12 },
  { surahNumber: 66, name: 'At-Tahrim', ayahCount: 12 },
  { surahNumber: 67, name: 'Al-Mulk', ayahCount: 30 },
  { surahNumber: 68, name: 'Al-Qalam', ayahCount: 52 },
  { surahNumber: 69, name: 'Al-Haqqah', ayahCount: 52 },
  { surahNumber: 70, name: "Al-Ma'arij", ayahCount: 44 },
  { surahNumber: 71, name: 'Nuh', ayahCount: 28 },
  { surahNumber: 72, name: 'Al-Jinn', ayahCount: 28 },
  { surahNumber: 73, name: 'Al-Muzzammil', ayahCount: 20 },
  { surahNumber: 74, name: 'Al-Muddathir', ayahCount: 56 },
  { surahNumber: 75, name: 'Al-Qiyamah', ayahCount: 40 },
  { surahNumber: 76, name: 'Al-Insan', ayahCount: 31 },
  { surahNumber: 77, name: 'Al-Mursalat', ayahCount: 50 },
  { surahNumber: 78, name: "An-Naba'", ayahCount: 40 },
  { surahNumber: 79, name: "An-Nazi'at", ayahCount: 46 },
  { surahNumber: 80, name: 'Abasa', ayahCount: 42 },
  { surahNumber: 81, name: 'At-Takwir', ayahCount: 29 },
  { surahNumber: 82, name: 'Al-Infitar', ayahCount: 19 },
  { surahNumber: 83, name: 'Al-Mutaffifin', ayahCount: 36 },
  { surahNumber: 84, name: 'Al-Inshiqaq', ayahCount: 25 },
  { surahNumber: 85, name: 'Al-Buruj', ayahCount: 22 },
  { surahNumber: 86, name: 'At-Tariq', ayahCount: 17 },
  { surahNumber: 87, name: "Al-A'la", ayahCount: 19 },
  { surahNumber: 88, name: 'Al-Ghashiyah', ayahCount: 26 },
  { surahNumber: 89, name: 'Al-Fajr', ayahCount: 30 },
  { surahNumber: 90, name: 'Al-Balad', ayahCount: 20 },
  { surahNumber: 91, name: 'Ash-Shams', ayahCount: 15 },
  { surahNumber: 92, name: 'Al-Layl', ayahCount: 21 },
  { surahNumber: 93, name: 'Ad-Duha', ayahCount: 11 },
  { surahNumber: 94, name: 'Ash-Sharh', ayahCount: 8 },
  { surahNumber: 95, name: 'At-Tin', ayahCount: 8 },
  { surahNumber: 96, name: 'Al-Alaq', ayahCount: 19 },
  { surahNumber: 97, name: 'Al-Qadr', ayahCount: 5 },
  { surahNumber: 98, name: 'Al-Bayyinah', ayahCount: 8 },
  { surahNumber: 99, name: 'Az-Zalzalah', ayahCount: 8 },
  { surahNumber: 100, name: 'Al-Adiyat', ayahCount: 11 },
  { surahNumber: 101, name: "Al-Qari'ah", ayahCount: 11 },
  { surahNumber: 102, name: 'At-Takathur', ayahCount: 8 },
  { surahNumber: 103, name: 'Al-Asr', ayahCount: 3 },
  { surahNumber: 104, name: 'Al-Humazah', ayahCount: 9 },
  { surahNumber: 105, name: 'Al-Fil', ayahCount: 5 },
  { surahNumber: 106, name: 'Quraysh', ayahCount: 4 },
  { surahNumber: 107, name: "Al-Ma'un", ayahCount: 7 },
  { surahNumber: 108, name: 'Al-Kawthar', ayahCount: 3 },
  { surahNumber: 109, name: 'Al-Kafirun', ayahCount: 6 },
  { surahNumber: 110, name: 'An-Nasr', ayahCount: 3 },
  { surahNumber: 111, name: 'Al-Masad', ayahCount: 5 },
  { surahNumber: 112, name: 'Al-Ikhlas', ayahCount: 4 },
  { surahNumber: 113, name: 'Al-Falaq', ayahCount: 5 },
  { surahNumber: 114, name: 'An-Nas', ayahCount: 6 },
]
